---
- name: ansibleTask
  hosts: ubuntu01
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: true

    - name: Install OpenJDK
      apt:
        name: openjdk-8-jre-headless
        state: present
      become: true

    - name: Install Maven
      apt:
        name: maven
        state: present
      become: true

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      become: true

    - name: Run Docker Hello World
      command: docker run hello-world
      become: true
